name: Deploy FE to EC2
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # AWS creds ➜ ECR push
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - run: |
          docker build -t waterandfish-frontend:latest .
          docker tag  waterandfish-frontend:latest \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/waterandfish-frontend:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/waterandfish-frontend:latest

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          sync: true                # 깃 저장소 전체 복사
          script: |
            # 1) AWS CLI (없으면 설치)
            if ! command -v aws >/dev/null; then
              sudo apt-get update -y && sudo apt-get install -y unzip
              curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/aws.zip
              unzip -qq /tmp/aws.zip -d /tmp && sudo /tmp/aws/install
            fi
            # 2) ECR 로그인 & 이미지 최신화
            aws ecr get-login-password --region ap-northeast-2 \
            | docker login --username AWS --password-stdin \
              ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com
            docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/waterandfish-frontend:latest
            # 3) 서비스 재기동
            docker stop frontend || true && docker rm frontend || true
            docker run -d --name frontend -p 80:80 \
              --env-file .env.production \
              -v $PWD/ssl:/etc/nginx/ssl \
              ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/waterandfish-frontend:latest
