name: Deploy FE to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Upload to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/team5-waterandfish-FE"

      - name: SSH and run Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/team5-waterandfish-FE
            docker build -t waterandfish-fe .
            docker stop waterandfish-frontend || true
            docker rm waterandfish-frontend || true
            docker run -d -p 80:80 --name waterandfish-frontend waterandfish-fe